### ISSUE TITLE
事前ミッション: git, docker, golangの環境を用意する

### ISSUE THREAD

**Issue by saxsir** [voyagegroup/hakaru#50]
Sunriseに参加するための事前課題です！Sunrise本番でみなさんがスムーズに開発に入れるよう、事前に動作確認をすることを目的としています。

下記のチェック項目が手元で確認できればOKですので、必ず本番までにやってきてください！
詰まるところがあればslack, Facebookグループ, issue立てるとかなんでもいいので気軽に聞いてくださいね。

## 事前ミッション

1. https://github.com/voyagegroup/hakaru を手元にcloneしてくる
  * GOPATH配下に置くこと（この説明で分かったら素晴らしい）

※ goが入ってない人向け
https://golang.org/doc/install を見てインストールしましょう。
デフォルトだとGOPATHは `$HOME/go`  になります。

なので、

> GOPATH配下に置くこと

イコール、 `$HOME/go/src/github.com/voyagegroup/hakaru`

にcloneしてきたリポジトリがあれば大丈夫です。

2. 下記コマンドが動くこと

※ Windowsの場合は細かいコマンドが違うかもしれないので、仮想環境（VirtualBox等）を推奨します

```
# cloneしてきたリポジトリルートで作業
$ go env | grep GOPATH
GOPATH="/Users/s-sasamoto/go"

$ pwd
/Users/s-sasamoto/go/src/github.com/voyagegroup/hakaru

$ make -C db setup
/Applications/Xcode.app/Contents/Developer/usr/bin/make mysql/setup mysql/run
docker pull mysql:latest
latest: Pulling from library/mysql

...

sleep 20 # for mysql service

...

+----------------+-------------------------------------------------------------------+---------------------+---------+
| Version        | Description                                                       | Installed on        | State   |
+----------------+-------------------------------------------------------------------+---------------------+---------+
| 1              | << Flyway Init >>                                                 | 2018-11-30 07:08:40 | Success |
| 2              | crate table event log                                             | 2018-11-30 07:08:43 | Success |
+----------------+-------------------------------------------------------------------+---------------------+---------+

# mysqlのcontainerが動いてればOK
$ docker ps
CONTAINER ID        IMAGE               COMMAND                  CREATED              STATUS              PORTS                                NAMES
6bb6c999cab1        mysql:latest        "docker-entrypoint.s…"   About a minute ago   Up About a minute   33060/tcp, 0.0.0.0:13306->3306/tcp   hakaru-mysql
```

```
$ pwd
/Users/s-sasamoto/go/src/github.com/voyagegroup/hakaru

$ make
test -x /Users/s-sasamoto/bin/dep || go get github.com/golang/dep/...
/Users/s-sasamoto/bin/dep ensure -v -vendor-only=true
(1/2) Wrote github.com/go-sql-driver/mysql@v1.4.0
(2/2) Wrote google.golang.org/appengine@v1.1.0
go run main.go
```

別のターミナルウィンドウを開いて、アプリが立ち上がってることを確認する。

```
$ curl -i localhost:8081/ok
HTTP/1.1 200 OK
Date: Fri, 30 Nov 2018 07:10:39 GMT
Content-Length: 0
```

無事にアプリケーションが立ち上がって、アクセスが確認できればOKです！

## Goをあまり書いたことがない人向け

[main.go](https://github.com/voyagegroup/hakaru/blob/master/main.go) を読んでみてください。
当日は負荷を捌くための手段として、このアプリケーションの改修もあり得るのでどういう処理が行われているか理解していると早いです。

また、Goには [A Tour of Go](https://tour.golang.org/list) という学習サイトがあるので、そこで基礎文法を学ぶのも良いでしょう。（日本語に翻訳されたページもあります）

`Basics` のところは抑えておくのと、チームによっては `Concurrency` も使いたくなるかもしれません。

あと時間がある人は [Effective Go](https://golang.org/doc/effective_go.html) や [github.com/golang/go/wiki/CodeReviewComments](https://github.com/golang/go/wiki/CodeReviewComments) はGoのコードを書くにあたって参考になります。（いわゆるGoらしく書くとどうやって書くのか？とか）

ただ、今回はGoを学ぶインターンではないので [main.go](https://github.com/voyagegroup/hakaru/blob/master/main.go) が読めれば大丈夫です。

分からないところ、動かないところがあればこのissueにコメントやslackで聞いてみてください！

**Comment by yoshikawataiki** [comment]
@saxsir DONE🎉

**Comment by naro143** [comment]
@saxsir DONE :)
